---
# tasks file for mongo-connector
- name: LEADER | STACK | COPY COMPOSE MONGO CONNECT
  template:
    src: "docker-compose-stack-mongo-connector.j2"
    dest: "/root/docker-compose-stack-mongo-connector.yml"
    owner: root
    mode : "0755"
  when: '"leader" in group_names'
- name: LEADER | STACK | DEPLOY MONGO CONNECT
  command: "docker stack deploy --compose-file /root/docker-compose-stack-mongo-connector.yml mongo-connector"
  when: '"leader" in group_names'